MIN_ASTEROID_DENSITY = 12
MAX_ASTEROID_DENSITY = 32
PROJECTILE_FRAME_RATE = 0.08

DEFAULT_SENSOR_RANGE = 5
DEFAULT_FUEL_CAPACITY = 100

IS_TURNING_RESTRICTED = false
IS_FIRING_RESTRICTED = false
IS_SPEED_RESTRICTED = false

CONTINUE_MOVING_THROUGH_WAYGATE = true